# config.yaml - Main configuration file
model:
  name: "microsoft/DialoGPT-small"  # Options: microsoft/DialoGPT-small, gpt2, facebook/opt-350m
  
dataset:
  name: "squad"  # Options: squad, natural_questions
  max_train_samples: 1000
  max_test_samples: 200
  
training:
  epochs: 3
  batch_size: 4
  gradient_accumulation_steps: 2
  learning_rate: 5e-5
  warmup_steps: 100
  
evaluation:
  similarity_threshold: 0.5  # For more sophisticated answer evaluation
  
paths:
  output_dir: "./epistemic_experiment_results"
  cache_dir: "./cache"

---

# requirements.txt
torch>=1.9.0
transformers>=4.20.0
datasets>=2.0.0
numpy>=1.21.0
pandas>=1.3.0
scikit-learn>=1.0.0
matplotlib>=3.5.0
seaborn>=0.11.0
tqdm>=4.62.0
pyyaml>=6.0
accelerate>=0.20.0
evaluate>=0.4.0

# Optional for advanced features
# sentence-transformers>=2.0.0  # For semantic similarity evaluation
# wandb>=0.13.0  # For experiment tracking

---

# setup.sh - Setup script
#!/bin/bash

echo "Setting up Epistemic Humility Experiment Environment..."

# Create virtual environment
python -m venv epistemic_env
source epistemic_env/bin/activate  # On Windows: epistemic_env\Scripts\activate

# Upgrade pip
pip install --upgrade pip

# Install requirements
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118  # For CUDA 11.8
pip install transformers datasets numpy pandas scikit-learn matplotlib seaborn tqdm pyyaml accelerate evaluate

# Create directories
mkdir -p data
mkdir -p results
mkdir -p cache

echo "Setup complete! Activate environment with: source epistemic_env/bin/activate"
echo "Run experiment with: python epistemic_experiment.py"

---

# advanced_config.yaml - For larger models and datasets
model:
  name: "microsoft/DialoGPT-medium"  # or "gpt2-medium", "facebook/opt-1.3b"
  
dataset:
  name: "squad"
  max_train_samples: 5000
  max_test_samples: 1000
  
training:
  epochs: 2
  batch_size: 2
  gradient_accumulation_steps: 8
  learning_rate: 3e-5
  warmup_steps: 200
  weight_decay: 0.01
  
evaluation:
  use_semantic_similarity: true
  similarity_threshold: 0.7
  
paths:
  output_dir: "./large_experiment_results"
  cache_dir: "./cache"
  
# Axolotl integration settings (if using Axolotl for training)
axolotl:
  use_axolotl: false
  config_path: "./axolotl_config.yaml"